# Generated by Django 3.2.7 on 2021-09-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='content_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='content_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='content_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
