# Generated by Django 2.2.5 on 2019-09-28 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190928_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='last_submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Submission Date'),
        ),
    ]
