# Generated by Django 3.1.5 on 2021-01-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190928_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
