# Generated by Django 2.2.16 on 2021-01-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofileinfo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='discord_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
