# Generated by Django 3.1.5 on 2022-01-23 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210608_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='member_since',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Member since'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='member_until',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Member until'),
        ),
    ]
