# Generated by Django 3.2.7 on 2021-10-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
