# Generated by Django 3.1.5 on 2021-12-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211227_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventplayer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.team'),
        ),
        migrations.AlterField(
            model_name='eventplayer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
