# Generated by Django 3.1.5 on 2021-12-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211215_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplayer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.team'),
        ),
    ]
