# Generated by Django 3.1.5 on 2022-01-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211227_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='size',
        ),
        migrations.AddField(
            model_name='team',
            name='auto',
            field=models.BooleanField(default=False),
        ),
    ]
