# Generated by Django 3.1.5 on 2022-01-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220114_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_match',
            field=models.BooleanField(default=False),
        ),
    ]
