# Generated by Django 3.1.5 on 2022-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_auto_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dynamic',
            field=models.BooleanField(default=False),
        ),
    ]
