# Generated by Django 2.2.5 on 2019-09-29 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CTF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=48)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='challenges')),
                ('ctf_url', models.URLField(blank=True)),
                ('points', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=55)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctfs.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CTF_flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_date', models.DateTimeField(verbose_name='Flag date')),
                ('ctf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctfs.CTF')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solution',
                'verbose_name_plural': 'solutions',
                'ordering': ['-flag_date'],
            },
        ),
    ]
