# Generated by Django 2.2.6 on 2019-10-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfs', '0002_auto_20190929_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctf',
            name='flag',
            field=models.CharField(max_length=100),
        ),
    ]
