# Generated by Django 3.2.7 on 2021-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfs', '0003_auto_20191003_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctf',
            name='description_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ctf',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ctf',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
    ]
